library("ggplot2")
xyplot(mpg~disp,data=mtcars,groups=cyl,auto.key=list(corner=c(1,1)))
qplot(disp,mpg,data=mtcars,col=as.factor(cyl))
qplot(disp,mpg,data=mtcars,shape=as.factor(cyl))
qplot(disp,mpg,data=mtcars,size=as.factor(cyl))
dsmall <- diamonds[sample(nrow(diamonds),100),]
qplot(carat,price,data=diamonds)
qplot(log(carat),log(price),data=diamonds)
qplot(carat,x*y*z,data=diamonds)
qplot(carat,price,data=dsmall,colour=color)
qplot(carat,price,data=dsmall,shape=cut)
qplot(carat,price,data=diamonds,alpha=I(1/200))
qplot(carat,price,data=diamonds,geom=c("point","smooth"))
qplot(carat,price,data=dsmall,geom=c("point","smooth"),span=0.2)
qplot(carat,price,data=dsmall,geom=c("point","smooth"),span=0.5)
library(mgcv)
qplot(carat,price,data=dsmall,geom=c("point","smooth"),method="gam",formula=y ~ s(x))
qplot(carat,price,data=dsmall,geom=c("point","smooth"),method="gam",formula=y~s(x,bs="cs"))
qplot(color,price/carat,data=diamonds,geom="jitter",alpha=I(1/5))
qplot(color,price/carat,data=diamonds,geom="boxplot")
qplot(carat,data=diamonds,geom="histogram",binwidth=1,xlim=c(0,3))
qplot(carat,data=diamonds,geom="density",colour=color)
qplot(carat,data=diamonds,geom="histogram",fill=color)
qplot(color,data=diamonds,geom="bar",fill=color)
qplot(color,data=diamonds,geom="bar",fill=color,weight=carat)+
  scale_y_continuous("carat")

qplot(date,unemploy/pop,data=economics,geom="line")
qplot(date,uempmed,data=economics,geom="line")
year<-function(x) as.POSIXlt(x)$year + 1900
qplot(unemploy/pop,uempmed,data=economics,geom=c("point","path"))
qplot(unemploy/pop,uempmed,data=economics,geom="path",colour=year(date))
qplot(carat,data=diamonds,facets=color~.,geom="histogram",binwidth=0.1,xlim=c(0,3))
qplot(carat,..density..,data=diamonds,facets=color ~.,geom="histogram",binwidth=0.1,xlim=c(0,3))
qplot(carat,price,data=dsmall,colour=price,xlab="Price($)",ylab="weight(carats)",main="Price-weight relationship")
qplot(carat,price/carat,data=dsmall,colour=carat,ylab=expression(frac(price,carat)),xlab="Weight(carat)",main="Small diamonds",xlim=c(.2,1))
qplot(carat,price,data=dsmall,log="xy",geom=c("point","smooth"),colour=price)

qplot(displ,hwy,data=mpg,colour=factor(cyl))
qplot(displ,hwy,data=mpg,facets=.~year)+geom_smooth()
